# Generated by Django 4.2.27 on 2026-01-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('repo_full_name', models.CharField(help_text='GitHub repo in format: owner/repo (e.g., bradshawrc93/project-name)', max_length=200)),
                ('tagline', models.CharField(help_text='Short description', max_length=300)),
                ('stack', models.CharField(help_text='Comma-separated tech stack (e.g., Python, Django, PostgreSQL)', max_length=500)),
                ('demo_url', models.URLField(blank=True, help_text='Optional demo/live site URL', null=True)),
                ('featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('planning', 'Planning')], default='active', max_length=20)),
                ('sort_order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
