# Generated by Django 4.2.27 on 2026-01-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepoSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_full_name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('language', models.CharField(blank=True, max_length=100)),
                ('stars', models.IntegerField(default=0)),
                ('forks', models.IntegerField(default=0)),
                ('open_issues', models.IntegerField(default=0)),
                ('pushed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='UserContributionDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=100)),
                ('day', models.DateField(db_index=True)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-day'],
                'indexes': [models.Index(fields=['username', '-day'], name='githubsync__usernam_4601ce_idx')],
                'unique_together': {('username', 'day')},
            },
        ),
        migrations.CreateModel(
            name='RepoActivityPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_full_name', models.CharField(db_index=True, max_length=200)),
                ('day', models.DateField(db_index=True)),
                ('commits', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-day'],
                'indexes': [models.Index(fields=['repo_full_name', '-day'], name='githubsync__repo_fu_8ffa9e_idx')],
                'unique_together': {('repo_full_name', 'day')},
            },
        ),
    ]
