# Generated by Django 4.2.27 on 2026-01-02 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('githubsync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reposnapshot',
            name='readme_content',
            field=models.TextField(blank=True, help_text='README.md content from repository'),
        ),
    ]
