# Generated by Django 4.2.27 on 2026-01-02 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('githubsync', '0002_reposnapshot_readme_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reposnapshot',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
